import csv
from decimal import Decimal, InvalidOperation
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError

from api.models import FuelStation


US_STATES = set(
    "AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO "
    "MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI DC"
    .split()
)

BATCH_SIZE = 500
PROGRESS_INTERVAL = 500


def normalize(value):
    return " ".join(str(value or "").strip().upper().split())


class Command(BaseCommand):
    help = "Import the supplied fuel-price CSV into the local station database."

    def add_arguments(self, parser):
        parser.add_argument(
            "--file",
            default="data/fuel-prices-for-be-assessment.csv",
            help="CSV path relative to the project root.",
        )
        parser.add_argument(
            "--city-centroids",
            default="data/city_centroids.csv",
            help="City centroid lookup generated by build_city_centroids.",
        )
        parser.add_argument(
            "--skip-missing-coordinates",
            action="store_true",
            help="Import stations even when no city centroid is available.",
        )
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete existing stations before importing.",
        )

    def handle(self, *args, **options):
        csv_path = Path(options["file"])
        centroid_path = Path(options["city_centroids"])

        if not csv_path.exists():
            raise CommandError(f"Fuel CSV not found: {csv_path}")

        if not centroid_path.exists() and not options["skip_missing_coordinates"]:
            raise CommandError(
                f"City centroid lookup not found: {centroid_path}. "
                "Run `python manage.py build_city_centroids` first."
            )

        self.stdout.write("Loading city centroid data...")

        centroids = {}

        if centroid_path.exists():
            with centroid_path.open(
                newline="",
                encoding="utf-8",
            ) as fh:
                for row in csv.DictReader(fh):
                    city = normalize(row["city"])
                    state = normalize(row["state"])

                    centroids[(city, state)] = (
                        float(row["latitude"]),
                        float(row["longitude"]),
                    )

        self.stdout.write(
            self.style.SUCCESS(
                f"Loaded {len(centroids):,} city centroids."
            )
        )

        if options["clear"]:
            deleted, _ = FuelStation.objects.all().delete()

            self.stdout.write(
                self.style.WARNING(
                    f"Cleared {deleted:,} existing database records."
                )
            )

        self.stdout.write("Reading fuel-price CSV...")

        # ------------------------------------------------------------------
        # First pass: read and validate CSV rows.
        # ------------------------------------------------------------------

        valid_rows = []
        skipped = 0

        with csv_path.open(
            newline="",
            encoding="utf-8-sig",
        ) as fh:
            reader = csv.DictReader(fh)

            for row_number, row in enumerate(reader, start=1):
                state = normalize(row.get("State"))

                if state not in US_STATES:
                    skipped += 1
                    continue

                city = normalize(row.get("City"))
                key = (city, state)
                coords = centroids.get(key)

                if coords is None and not options["skip_missing_coordinates"]:
                    skipped += 1
                    continue

                try:
                    truckstop_id = int(row["OPIS Truckstop ID"])
                    rack_id = (
                        int(row["Rack ID"])
                        if row.get("Rack ID")
                        else None
                    )
                    retail_price = Decimal(
                        str(row["Retail Price"]).strip()
                    )
                except (
                    KeyError,
                    ValueError,
                    InvalidOperation,
                ):
                    skipped += 1
                    continue

                valid_rows.append(
                    {
                        "truckstop_id": truckstop_id,
                        "name": row["Truckstop Name"].strip(),
                        "address": row["Address"].strip(),
                        "city": row["City"].strip(),
                        "state": state,
                        "rack_id": rack_id,
                        "retail_price": retail_price,
                        "latitude": coords[0] if coords else None,
                        "longitude": coords[1] if coords else None,
                        "location_source": (
                            "city_centroid"
                            if coords
                            else "missing"
                        ),
                    }
                )

                if row_number % PROGRESS_INTERVAL == 0:
                    self.stdout.write(
                        f"  Processed {row_number:,} CSV rows..."
                    )

        total_rows = len(valid_rows) + skipped

        self.stdout.write(
            self.style.SUCCESS(
                f"Validated {len(valid_rows):,} stations "
                f"from {total_rows:,} CSV rows."
            )
        )

        if not valid_rows:
            self.stdout.write(
                self.style.WARNING(
                    "No valid stations found to import."
                )
            )
            return

        # ------------------------------------------------------------------
        # Build existing station keys once.
        #
        # This avoids one database query per CSV row.
        # ------------------------------------------------------------------

        self.stdout.write("Checking existing stations...")

        existing_keys = set(
            FuelStation.objects.values_list(
                "truckstop_id",
                "name",
                "address",
                "city",
                "state",
            )
        )

        objects_to_create = []
        duplicates = 0

        for item in valid_rows:
            key = (
                item["truckstop_id"],
                item["name"],
                item["address"],
                item["city"],
                item["state"],
            )

            if key in existing_keys:
                duplicates += 1
                continue

            objects_to_create.append(
                FuelStation(
                    truckstop_id=item["truckstop_id"],
                    name=item["name"],
                    address=item["address"],
                    city=item["city"],
                    state=item["state"],
                    rack_id=item["rack_id"],
                    retail_price=item["retail_price"],
                    latitude=item["latitude"],
                    longitude=item["longitude"],
                    location_source=item["location_source"],
                )
            )

            # Prevent duplicates inside the same CSV from being inserted.
            existing_keys.add(key)

        self.stdout.write(
            f"Preparing {len(objects_to_create):,} new stations..."
        )

        # ------------------------------------------------------------------
        # Bulk insert.
        # ------------------------------------------------------------------

        created = 0

        for start in range(
            0,
            len(objects_to_create),
            BATCH_SIZE,
        ):
            batch = objects_to_create[
                start : start + BATCH_SIZE
            ]

            FuelStation.objects.bulk_create(
                batch,
                batch_size=BATCH_SIZE,
            )

            created += len(batch)

            self.stdout.write(
                f"  Imported {created:,}/{len(objects_to_create):,} stations..."
            )

        self.stdout.write("")

        self.stdout.write(
            self.style.SUCCESS(
                "Fuel import complete!"
            )
        )

        self.stdout.write(
            self.style.SUCCESS(
                f"Imported {created:,} stations; "
                f"skipped {skipped:,}; "
                f"duplicates {duplicates:,}."
            )
        )